import React from 'react';
import * as Icons from '@ant-design/icons';

// Map of icon names to their components
const iconMap: Record<string, React.ReactNode> = {
    // Money & Finance
    'dollar': <Icons.DollarOutlined />,
    'dollar-circle': <Icons.DollarCircleOutlined />,
    'money-collect': <Icons.MoneyCollectOutlined />,
    'fund': <Icons.FundOutlined />,
    'fund-projection-screen': <Icons.FundProjectionScreenOutlined />,
    'fund-view': <Icons.FundViewOutlined />,
    'stock': <Icons.StockOutlined />,
    'rise': <Icons.RiseOutlined />,
    'fall': <Icons.FallOutlined />,
    'line-chart': <Icons.LineChartOutlined />,
    'bar-chart': <Icons.BarChartOutlined />,
    'pie-chart': <Icons.PieChartOutlined />,
    'area-chart': <Icons.AreaChartOutlined />,
    'wallet': <Icons.WalletOutlined />,
    'bank': <Icons.BankOutlined />,
    'credit-card': <Icons.CreditCardOutlined />,
    'insurance': <Icons.InsuranceOutlined />,
    'transaction': <Icons.TransactionOutlined />,
    'pay-circle': <Icons.PayCircleOutlined />,
    'red-envelope': <Icons.RedEnvelopeOutlined />,
    'account-book': <Icons.AccountBookOutlined />,
    'calculator': <Icons.CalculatorOutlined />,
    'property-safety': <Icons.PropertySafetyOutlined />,
    'audit': <Icons.AuditOutlined />,
    'percentage': <Icons.PercentageOutlined />,

    // Shopping & Commerce
    'shopping-cart': <Icons.ShoppingCartOutlined />,
    'shopping': <Icons.ShoppingOutlined />,
    'shop': <Icons.ShopOutlined />,
    'skin': <Icons.SkinOutlined />,
    'gift': <Icons.GiftOutlined />,
    'barcode': <Icons.BarcodeOutlined />,
    'qrcode': <Icons.QrcodeOutlined />,
    'tag': <Icons.TagOutlined />,
    'tags': <Icons.TagsOutlined />,
    'gold': <Icons.GoldOutlined />,
    'trophy': <Icons.TrophyOutlined />,
    'crown': <Icons.CrownOutlined />,

    // Home & Living
    'home': <Icons.HomeOutlined />,
    'apartment': <Icons.ApartmentOutlined />,
    'build': <Icons.BuildOutlined />,
    'tool': <Icons.ToolOutlined />,
    'setting': <Icons.SettingOutlined />,
    'control': <Icons.ControlOutlined />,
    'sliders': <Icons.SlidersOutlined />,
    'bulb': <Icons.BulbOutlined />,
    'thunderbolt': <Icons.ThunderboltOutlined />,
    'fire': <Icons.FireOutlined />,
    'experiment': <Icons.ExperimentOutlined />,
    'key': <Icons.KeyOutlined />,
    'lock': <Icons.LockOutlined />,
    'unlock': <Icons.UnlockOutlined />,
    'wifi': <Icons.WifiOutlined />,
    'clear': <Icons.ClearOutlined />,
    'inbox': <Icons.InboxOutlined />,

    // Transport & Travel
    'car': <Icons.CarOutlined />,
    'rocket': <Icons.RocketOutlined />,
    'send': <Icons.SendOutlined />,
    'compass': <Icons.CompassOutlined />,
    'environment': <Icons.EnvironmentOutlined />,
    'global': <Icons.GlobalOutlined />,
    'aim': <Icons.AimOutlined />,

    // Food & Drinks
    'coffee': <Icons.CoffeeOutlined />,
    'apple': <Icons.AppleOutlined />,

    // Health & Medical
    'heart': <Icons.HeartOutlined />,
    'medicine-box': <Icons.MedicineBoxOutlined />,
    'safety': <Icons.SafetyOutlined />,
    'safety-certificate': <Icons.SafetyCertificateOutlined />,
    'user-switch': <Icons.UserSwitchOutlined />,

    // Entertainment & Leisure
    'smile': <Icons.SmileOutlined />,
    'meh': <Icons.MehOutlined />,
    'frown': <Icons.FrownOutlined />,
    'play-circle': <Icons.PlayCircleOutlined />,
    'play-square': <Icons.PlaySquareOutlined />,
    'pause-circle': <Icons.PauseCircleOutlined />,
    'video-camera': <Icons.VideoCameraOutlined />,
    'camera': <Icons.CameraOutlined />,
    'picture': <Icons.PictureOutlined />,
    'sound': <Icons.SoundOutlined />,
    'customer-service': <Icons.CustomerServiceOutlined />,
    'youtube': <Icons.YoutubeOutlined />,

    // Education & Work
    'book': <Icons.BookOutlined />,
    'read': <Icons.ReadOutlined />,
    'highlight': <Icons.HighlightOutlined />,
    'edit': <Icons.EditOutlined />,
    'form': <Icons.FormOutlined />,
    'file': <Icons.FileOutlined />,
    'file-text': <Icons.FileTextOutlined />,
    'file-pdf': <Icons.FilePdfOutlined />,
    'file-excel': <Icons.FileExcelOutlined />,
    'file-word': <Icons.FileWordOutlined />,
    'file-ppt': <Icons.FilePptOutlined />,
    'file-image': <Icons.FileImageOutlined />,
    'file-zip': <Icons.FileZipOutlined />,
    'file-search': <Icons.FileSearchOutlined />,
    'file-done': <Icons.FileDoneOutlined />,
    'file-protect': <Icons.FileProtectOutlined />,
    'folder': <Icons.FolderOutlined />,
    'folder-open': <Icons.FolderOpenOutlined />,
    'solution': <Icons.SolutionOutlined />,
    'profile': <Icons.ProfileOutlined />,
    'project': <Icons.ProjectOutlined />,
    'schedule': <Icons.ScheduleOutlined />,
    'snippets': <Icons.SnippetsOutlined />,
    'idcard': <Icons.IdcardOutlined />,
    'container': <Icons.ContainerOutlined />,
    'database': <Icons.DatabaseOutlined />,
    'table': <Icons.TableOutlined />,
    'layout': <Icons.LayoutOutlined />,
    'appstore': <Icons.AppstoreOutlined />,
    'laptop': <Icons.LaptopOutlined />,
    'desktop': <Icons.DesktopOutlined />,
    'tablet': <Icons.TabletOutlined />,
    'mobile': <Icons.MobileOutlined />,
    'code': <Icons.CodeOutlined />,
    'api': <Icons.ApiOutlined />,
    'cloud': <Icons.CloudOutlined />,
    'cluster': <Icons.ClusterOutlined />,
    'deployment-unit': <Icons.DeploymentUnitOutlined />,

    // People & Social
    'user': <Icons.UserOutlined />,
    'team': <Icons.TeamOutlined />,
    'usergroup-add': <Icons.UsergroupAddOutlined />,
    'user-add': <Icons.UserAddOutlined />,
    'contacts': <Icons.ContactsOutlined />,
    'phone': <Icons.PhoneOutlined />,
    'mail': <Icons.MailOutlined />,
    'message': <Icons.MessageOutlined />,
    'comment': <Icons.CommentOutlined />,
    'notification': <Icons.NotificationOutlined />,
    'bell': <Icons.BellOutlined />,
    'like': <Icons.LikeOutlined />,
    'dislike': <Icons.DislikeOutlined />,
    'share-alt': <Icons.ShareAltOutlined />,
    'link': <Icons.LinkOutlined />,

    // Nature & Weather
    'sun': <Icons.SunOutlined />,
    'cloud-outlined': <Icons.CloudOutlined />,
    'bug': <Icons.BugOutlined />,

    // Sports & Activities
    'dribbble': <Icons.DribbbleOutlined />,
    'slack': <Icons.SlackOutlined />,
    'github': <Icons.GithubOutlined />,

    // Shapes & Symbols
    'star': <Icons.StarOutlined />,
    'flag': <Icons.FlagOutlined />,
    'pushpin': <Icons.PushpinOutlined />,
    'question': <Icons.QuestionOutlined />,
    'question-circle': <Icons.QuestionCircleOutlined />,
    'info': <Icons.InfoOutlined />,
    'info-circle': <Icons.InfoCircleOutlined />,
    'exclamation': <Icons.ExclamationOutlined />,
    'exclamation-circle': <Icons.ExclamationCircleOutlined />,
    'warning': <Icons.WarningOutlined />,
    'check': <Icons.CheckOutlined />,
    'check-circle': <Icons.CheckCircleOutlined />,
    'close': <Icons.CloseOutlined />,
    'close-circle': <Icons.CloseCircleOutlined />,
    'plus': <Icons.PlusOutlined />,
    'plus-circle': <Icons.PlusCircleOutlined />,
    'minus': <Icons.MinusOutlined />,
    'minus-circle': <Icons.MinusCircleOutlined />,
    'stop': <Icons.StopOutlined />,
    'clock-circle': <Icons.ClockCircleOutlined />,
    'calendar': <Icons.CalendarOutlined />,
    'hourglass': <Icons.HourglassOutlined />,
    'field-time': <Icons.FieldTimeOutlined />,
    'history': <Icons.HistoryOutlined />,
    'sync': <Icons.SyncOutlined />,
    'redo': <Icons.RedoOutlined />,
    'reload': <Icons.ReloadOutlined />,
    'rollback': <Icons.RollbackOutlined />,
    'filter': <Icons.FilterOutlined />,
    'search': <Icons.SearchOutlined />,
    'zoom-in': <Icons.ZoomInOutlined />,
    'zoom-out': <Icons.ZoomOutOutlined />,
    'eye': <Icons.EyeOutlined />,
    'eye-invisible': <Icons.EyeInvisibleOutlined />,

    // Arrows & Navigation
    'arrow-up': <Icons.ArrowUpOutlined />,
    'arrow-down': <Icons.ArrowDownOutlined />,
    'arrow-left': <Icons.ArrowLeftOutlined />,
    'arrow-right': <Icons.ArrowRightOutlined />,
    'swap': <Icons.SwapOutlined />,
    'vertical-align-top': <Icons.VerticalAlignTopOutlined />,
    'vertical-align-bottom': <Icons.VerticalAlignBottomOutlined />,
    'download': <Icons.DownloadOutlined />,
    'upload': <Icons.UploadOutlined />,
    'import': <Icons.ImportOutlined />,
    'export': <Icons.ExportOutlined />,
    'login': <Icons.LoginOutlined />,
    'logout': <Icons.LogoutOutlined />,
    'menu': <Icons.MenuOutlined />,
    'more': <Icons.MoreOutlined />,
    'ellipsis': <Icons.EllipsisOutlined />,
    'dash': <Icons.DashOutlined />,
    'border': <Icons.BorderOutlined />,
    'radius-setting': <Icons.RadiusSettingOutlined />,
    'fullscreen': <Icons.FullscreenOutlined />,
    'fullscreen-exit': <Icons.FullscreenExitOutlined />,
    'expand': <Icons.ExpandOutlined />,
    'compress': <Icons.CompressOutlined />,
    'column-width': <Icons.ColumnWidthOutlined />,
    'column-height': <Icons.ColumnHeightOutlined />,
    'drag': <Icons.DragOutlined />,
    'ordered-list': <Icons.OrderedListOutlined />,
    'unordered-list': <Icons.UnorderedListOutlined />,
    'holder': <Icons.HolderOutlined />,
    'gateway': <Icons.GatewayOutlined />,
    'partition': <Icons.PartitionOutlined />,
    'fork': <Icons.ForkOutlined />,
    'merge-cells': <Icons.MergeCellsOutlined />,
    'split-cells': <Icons.SplitCellsOutlined />,
    'branches': <Icons.BranchesOutlined />,
    'pull-request': <Icons.PullRequestOutlined />,
    'scissor': <Icons.ScissorOutlined />,
    'delete': <Icons.DeleteOutlined />,
    'copy': <Icons.CopyOutlined />,
    'save': <Icons.SaveOutlined />,
    'printer': <Icons.PrinterOutlined />,
    'scan': <Icons.ScanOutlined />,
    'usb': <Icons.UsbOutlined />,
    'thunderbolt-filled': <Icons.ThunderboltFilled />,
};

// Icon categories for the selector
export const iconCategories = [
    {
        label: 'Dinero y Finanzas',
        icons: [
            { value: 'dollar', label: 'Dólar' },
            { value: 'dollar-circle', label: 'Dólar círculo' },
            { value: 'money-collect', label: 'Colectar dinero' },
            { value: 'wallet', label: 'Billetera' },
            { value: 'bank', label: 'Banco' },
            { value: 'credit-card', label: 'Tarjeta' },
            { value: 'fund', label: 'Fondo' },
            { value: 'stock', label: 'Acciones' },
            { value: 'rise', label: 'Subida' },
            { value: 'fall', label: 'Bajada' },
            { value: 'line-chart', label: 'Gráfico línea' },
            { value: 'bar-chart', label: 'Gráfico barras' },
            { value: 'pie-chart', label: 'Gráfico torta' },
            { value: 'calculator', label: 'Calculadora' },
            { value: 'percentage', label: 'Porcentaje' },
            { value: 'account-book', label: 'Libro cuentas' },
            { value: 'audit', label: 'Auditoría' },
            { value: 'insurance', label: 'Seguro' },
            { value: 'transaction', label: 'Transacción' },
            { value: 'pay-circle', label: 'Pago' },
            { value: 'red-envelope', label: 'Sobre rojo' },
            { value: 'gold', label: 'Oro' },
            { value: 'trophy', label: 'Trofeo' },
            { value: 'crown', label: 'Corona' },
        ],
    },
    {
        label: 'Compras',
        icons: [
            { value: 'shopping-cart', label: 'Carrito' },
            { value: 'shopping', label: 'Bolsa compras' },
            { value: 'shop', label: 'Tienda' },
            { value: 'gift', label: 'Regalo' },
            { value: 'skin', label: 'Ropa' },
            { value: 'tag', label: 'Etiqueta' },
            { value: 'tags', label: 'Etiquetas' },
            { value: 'barcode', label: 'Código barras' },
        ],
    },
    {
        label: 'Hogar y Servicios',
        icons: [
            { value: 'home', label: 'Casa' },
            { value: 'apartment', label: 'Apartamento' },
            { value: 'build', label: 'Edificio' },
            { value: 'tool', label: 'Herramienta' },
            { value: 'setting', label: 'Configuración' },
            { value: 'bulb', label: 'Bombilla' },
            { value: 'thunderbolt', label: 'Electricidad' },
            { value: 'fire', label: 'Fuego/Gas' },
            { value: 'wifi', label: 'WiFi' },
            { value: 'key', label: 'Llave' },
            { value: 'lock', label: 'Candado' },
            { value: 'clear', label: 'Limpieza' },
        ],
    },
    {
        label: 'Transporte',
        icons: [
            { value: 'car', label: 'Auto' },
            { value: 'rocket', label: 'Cohete' },
            { value: 'send', label: 'Enviar' },
            { value: 'compass', label: 'Brújula' },
            { value: 'environment', label: 'Ubicación' },
            { value: 'global', label: 'Global' },
            { value: 'aim', label: 'Objetivo' },
        ],
    },
    {
        label: 'Comida y Bebidas',
        icons: [
            { value: 'coffee', label: 'Café' },
            { value: 'apple', label: 'Manzana' },
        ],
    },
    {
        label: 'Salud',
        icons: [
            { value: 'heart', label: 'Corazón' },
            { value: 'medicine-box', label: 'Medicina' },
            { value: 'safety', label: 'Seguridad' },
            { value: 'safety-certificate', label: 'Certificado' },
        ],
    },
    {
        label: 'Entretenimiento',
        icons: [
            { value: 'smile', label: 'Sonrisa' },
            { value: 'play-circle', label: 'Play' },
            { value: 'video-camera', label: 'Video' },
            { value: 'camera', label: 'Cámara' },
            { value: 'picture', label: 'Imagen' },
            { value: 'sound', label: 'Sonido' },
            { value: 'customer-service', label: 'Música' },
            { value: 'youtube', label: 'YouTube' },
            { value: 'dribbble', label: 'Deportes' },
        ],
    },
    {
        label: 'Educación y Trabajo',
        icons: [
            { value: 'book', label: 'Libro' },
            { value: 'read', label: 'Leer' },
            { value: 'edit', label: 'Editar' },
            { value: 'highlight', label: 'Resaltar' },
            { value: 'file', label: 'Archivo' },
            { value: 'file-text', label: 'Documento' },
            { value: 'folder', label: 'Carpeta' },
            { value: 'solution', label: 'Solución' },
            { value: 'project', label: 'Proyecto' },
            { value: 'schedule', label: 'Horario' },
            { value: 'idcard', label: 'Identificación' },
            { value: 'laptop', label: 'Laptop' },
            { value: 'desktop', label: 'Escritorio' },
            { value: 'mobile', label: 'Móvil' },
            { value: 'code', label: 'Código' },
            { value: 'api', label: 'API' },
            { value: 'cloud', label: 'Nube' },
            { value: 'database', label: 'Base datos' },
        ],
    },
    {
        label: 'Personas y Social',
        icons: [
            { value: 'user', label: 'Usuario' },
            { value: 'team', label: 'Equipo' },
            { value: 'contacts', label: 'Contactos' },
            { value: 'phone', label: 'Teléfono' },
            { value: 'mail', label: 'Correo' },
            { value: 'message', label: 'Mensaje' },
            { value: 'bell', label: 'Campana' },
            { value: 'notification', label: 'Notificación' },
            { value: 'like', label: 'Me gusta' },
            { value: 'share-alt', label: 'Compartir' },
        ],
    },
    {
        label: 'Tiempo y Calendario',
        icons: [
            { value: 'clock-circle', label: 'Reloj' },
            { value: 'calendar', label: 'Calendario' },
            { value: 'hourglass', label: 'Reloj arena' },
            { value: 'field-time', label: 'Tiempo' },
            { value: 'history', label: 'Historial' },
            { value: 'sync', label: 'Sincronizar' },
        ],
    },
    {
        label: 'Símbolos',
        icons: [
            { value: 'star', label: 'Estrella' },
            { value: 'flag', label: 'Bandera' },
            { value: 'pushpin', label: 'Pin' },
            { value: 'check-circle', label: 'Check' },
            { value: 'plus-circle', label: 'Más' },
            { value: 'minus-circle', label: 'Menos' },
            { value: 'question-circle', label: 'Pregunta' },
            { value: 'info-circle', label: 'Info' },
            { value: 'warning', label: 'Advertencia' },
            { value: 'ellipsis', label: 'Más opciones' },
            { value: 'filter', label: 'Filtro' },
            { value: 'search', label: 'Buscar' },
            { value: 'eye', label: 'Ver' },
            { value: 'download', label: 'Descargar' },
            { value: 'upload', label: 'Subir' },
            { value: 'delete', label: 'Eliminar' },
            { value: 'save', label: 'Guardar' },
            { value: 'printer', label: 'Imprimir' },
        ],
    },
];

// Flat list for simple select
export const iconOptions = iconCategories.flatMap((category) =>
    category.icons.map((icon) => ({
        ...icon,
        category: category.label,
    }))
);

export function getIcon(iconName: string | null | undefined): React.ReactNode {
    if (!iconName) return <Icons.TagOutlined />;
    return iconMap[iconName] || <Icons.TagOutlined />;
}

export { iconMap };
